version: '3.8'

services:
  panel:
    build:
      context: .
      network: host
    container_name: pnm-panel
    restart: unless-stopped
    network_mode: host
    volumes:
      - panel-data:/data
    environment:
      - NODE_ENV=production
      - DB_PATH=/data/panel.db
      - HOSTNAME=0.0.0.0

volumes:
  panel-data:
